version: '3.8'

services:
  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:?MONGO_ROOT_USERNAME environment variable is required}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:?MONGO_ROOT_PASSWORD environment variable is required}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    healthcheck:
      test: ["CMD", "mongosh", "-u", "${MONGO_ROOT_USERNAME}", "-p", "${MONGO_ROOT_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - default

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME:?MONGO_ROOT_USERNAME environment variable is required}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD:?MONGO_ROOT_PASSWORD environment variable is required}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_SITE_BASEURL=/
    depends_on:
      mongodb:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      # HTTP router (redirect to HTTPS)
      - "traefik.http.routers.mongo-express-http.rule=Host(`mongo.${DOMAIN}`)"
      - "traefik.http.routers.mongo-express-http.entrypoints=web"
      - "traefik.http.routers.mongo-express-http.middlewares=redirect-to-https"
      # HTTPS router with auth middleware
      - "traefik.http.routers.mongo-express-https.rule=Host(`mongo.${DOMAIN}`)"
      - "traefik.http.routers.mongo-express-https.entrypoints=websecure"
      - "traefik.http.routers.mongo-express-https.tls=true"
      - "traefik.http.routers.mongo-express-https.middlewares=auth-middleware"
      # Redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      # Service
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8081"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - default

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  default:
    name: traefik_network
    external: true
