version: '3.8'

services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    command:
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--ping=true"
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: marlene-web
    labels:
      - "traefik.enable=true"
      # HTTP router (redirect to HTTPS)
      - "traefik.http.routers.web-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.web-http.entrypoints=web"
      - "traefik.http.routers.web-http.middlewares=redirect-to-https"
      # HTTPS router
      - "traefik.http.routers.web-https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.web-https.entrypoints=websecure"
      - "traefik.http.routers.web-https.tls=true"
      - "traefik.http.routers.web-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.web-https.middlewares=strip-user-header,auth-middleware"
      # Redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      # Strip x-user header from client requests (security)
      - "traefik.http.middlewares.strip-user-header.headers.customrequestheaders.x-user="
      # Service
      - "traefik.http.services.web.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  auth-middleware:
    build:
      context: ./auth-middleware
      dockerfile: Dockerfile
    container_name: auth-middleware
    environment:
      - COOKIE_SECRET=${COOKIE_SECRET:?COOKIE_SECRET environment variable is required}
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY:?RESEND_API_KEY environment variable is required}
      - RESEND_FROM=${RESEND_FROM:-noreply@example.com}
    labels:
      - "traefik.enable=true"
      # Forward Auth middleware configuration
      - "traefik.http.middlewares.auth-middleware.forwardauth.address=http://auth-middleware:3000/auth"
      - "traefik.http.middlewares.auth-middleware.forwardauth.authRequestHeaders=Cookie"
      - "traefik.http.middlewares.auth-middleware.forwardauth.authResponseHeaders=x-user"
      - "traefik.http.middlewares.auth-middleware.forwardauth.addAuthCookiesToResponse=auth_token"
      # Direct routes for login and code pages (no auth middleware)
      - "traefik.http.routers.auth-pages.rule=Host(`${DOMAIN}`) && (PathPrefix(`/login`) || PathPrefix(`/code`))"
      - "traefik.http.routers.auth-pages.entrypoints=websecure"
      - "traefik.http.routers.auth-pages.priority=100"
      - "traefik.http.routers.auth-pages.tls=true"
      - "traefik.http.routers.auth-pages.tls.certresolver=letsencrypt"
      - "traefik.http.routers.auth-pages.service=auth-middleware"
      # Auth pages for mongo subdomain
      - "traefik.http.routers.auth-pages-mongo.rule=Host(`mongo.${DOMAIN}`) && (PathPrefix(`/login`) || PathPrefix(`/code`))"
      - "traefik.http.routers.auth-pages-mongo.entrypoints=websecure"
      - "traefik.http.routers.auth-pages-mongo.priority=100"
      - "traefik.http.routers.auth-pages-mongo.tls=true"
      - "traefik.http.routers.auth-pages-mongo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.auth-pages-mongo.service=auth-middleware"
      # Service
      - "traefik.http.services.auth-middleware.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
